name: Generate  Podcast Feeds
on: [push]
jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Run feed generator
              uses: darkweb19/learning-generator@main
